<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Activity;
use App\Models\Project;
use App\Models\User;
use Carbon\Carbon;

class ActivitySeeder extends Seeder
{
    public function run(): void
    {
        $projects = Project::all();
        $users = User::all();
        
        if ($projects->isEmpty() || $users->isEmpty()) {
            $this->command->info('No projects or users found. Skipping activity seeding.');
            return;
        }

        $activities = [
            [
                'title' => 'Project Setup and Planning',
                'description' => 'Initial project setup, team formation, and planning phase',
                'type' => 'task',
                'priority' => 'high',
                'status' => 'completed',
                'planned_start_date' => Carbon::now()->subDays(30),
                'planned_end_date' => Carbon::now()->subDays(25),
                'actual_start_date' => Carbon::now()->subDays(30),
                'actual_end_date' => Carbon::now()->subDays(25),
                'estimated_hours' => 40,
                'actual_hours' => 42,
                'progress_percentage' => 100,
                'estimated_cost' => 50000,
                'actual_cost' => 52000,
                'deliverables' => 'Project charter, team structure, initial timeline',
                'acceptance_criteria' => 'All planning documents approved by stakeholders',
                'completion_notes' => 'Successfully completed with minor adjustments to timeline',
                'is_milestone' => true,
                'is_billable' => true,
                'tags' => ['planning', 'setup', 'milestone'],
            ],
            [
                'title' => 'System Design and Architecture',
                'description' => 'Design system architecture and create technical specifications',
                'type' => 'task',
                'priority' => 'high',
                'status' => 'in_progress',
                'planned_start_date' => Carbon::now()->subDays(20),
                'planned_end_date' => Carbon::now()->subDays(10),
                'actual_start_date' => Carbon::now()->subDays(20),
                'actual_end_date' => null,
                'estimated_hours' => 60,
                'actual_hours' => 35,
                'progress_percentage' => 65,
                'estimated_cost' => 75000,
                'actual_cost' => 45000,
                'deliverables' => 'System architecture document, technical specifications',
                'acceptance_criteria' => 'Architecture approved by technical lead and stakeholders',
                'progress_notes' => 'Core architecture completed, working on detailed specifications',
                'is_milestone' => false,
                'is_billable' => true,
                'tags' => ['design', 'architecture', 'technical'],
            ],
            [
                'title' => 'Development Sprint 1',
                'description' => 'First development sprint focusing on core functionality',
                'type' => 'task',
                'priority' => 'high',
                'status' => 'in_progress',
                'planned_start_date' => Carbon::now()->subDays(15),
                'planned_end_date' => Carbon::now()->subDays(5),
                'actual_start_date' => Carbon::now()->subDays(15),
                'actual_end_date' => null,
                'estimated_hours' => 80,
                'actual_hours' => 55,
                'progress_percentage' => 70,
                'estimated_cost' => 100000,
                'actual_cost' => 75000,
                'deliverables' => 'Core modules, basic functionality',
                'acceptance_criteria' => 'All core features implemented and tested',
                'progress_notes' => 'Most core features completed, working on edge cases',
                'is_milestone' => false,
                'is_billable' => true,
                'tags' => ['development', 'sprint', 'core'],
            ],
            [
                'title' => 'Client Review Meeting',
                'description' => 'Present progress to client and gather feedback',
                'type' => 'meeting',
                'priority' => 'medium',
                'status' => 'planned',
                'planned_start_date' => Carbon::now()->addDays(2),
                'planned_end_date' => Carbon::now()->addDays(2),
                'actual_start_date' => null,
                'actual_end_date' => null,
                'estimated_hours' => 2,
                'actual_hours' => 0,
                'progress_percentage' => 0,
                'estimated_cost' => 5000,
                'actual_cost' => 0,
                'deliverables' => 'Progress presentation, feedback documentation',
                'acceptance_criteria' => 'Client approval for current progress',
                'is_milestone' => false,
                'is_billable' => true,
                'tags' => ['meeting', 'client', 'review'],
            ],
            [
                'title' => 'Quality Assurance Testing',
                'description' => 'Comprehensive testing of all developed features',
                'type' => 'task',
                'priority' => 'high',
                'status' => 'planned',
                'planned_start_date' => Carbon::now()->addDays(5),
                'planned_end_date' => Carbon::now()->addDays(15),
                'actual_start_date' => null,
                'actual_end_date' => null,
                'estimated_hours' => 50,
                'actual_hours' => 0,
                'progress_percentage' => 0,
                'estimated_cost' => 60000,
                'actual_cost' => 0,
                'deliverables' => 'Test reports, bug fixes, quality metrics',
                'acceptance_criteria' => 'All tests pass, no critical bugs',
                'is_milestone' => true,
                'is_billable' => true,
                'tags' => ['testing', 'qa', 'milestone'],
            ],
            [
                'title' => 'Documentation Creation',
                'description' => 'Create user manuals and technical documentation',
                'type' => 'task',
                'priority' => 'medium',
                'status' => 'planned',
                'planned_start_date' => Carbon::now()->addDays(10),
                'planned_end_date' => Carbon::now()->addDays(20),
                'actual_start_date' => null,
                'actual_end_date' => null,
                'estimated_hours' => 30,
                'actual_hours' => 0,
                'progress_percentage' => 0,
                'estimated_cost' => 35000,
                'actual_cost' => 0,
                'deliverables' => 'User manual, technical documentation, API docs',
                'acceptance_criteria' => 'Documentation reviewed and approved',
                'is_milestone' => false,
                'is_billable' => true,
                'tags' => ['documentation', 'manual', 'technical'],
            ],
            [
                'title' => 'Deployment and Go-Live',
                'description' => 'Deploy system to production and go live',
                'type' => 'delivery',
                'priority' => 'critical',
                'status' => 'planned',
                'planned_start_date' => Carbon::now()->addDays(25),
                'planned_end_date' => Carbon::now()->addDays(30),
                'actual_start_date' => null,
                'actual_end_date' => null,
                'estimated_hours' => 20,
                'actual_hours' => 0,
                'progress_percentage' => 0,
                'estimated_cost' => 25000,
                'actual_cost' => 0,
                'deliverables' => 'Live system, deployment documentation',
                'acceptance_criteria' => 'System running smoothly in production',
                'is_milestone' => true,
                'is_billable' => true,
                'tags' => ['deployment', 'production', 'milestone'],
            ],
            [
                'title' => 'Post-Launch Support',
                'description' => 'Provide support and maintenance after go-live',
                'type' => 'task',
                'priority' => 'medium',
                'status' => 'planned',
                'planned_start_date' => Carbon::now()->addDays(31),
                'planned_end_date' => Carbon::now()->addDays(60),
                'actual_start_date' => null,
                'actual_end_date' => null,
                'estimated_hours' => 40,
                'actual_hours' => 0,
                'progress_percentage' => 0,
                'estimated_cost' => 50000,
                'actual_cost' => 0,
                'deliverables' => 'Support tickets resolution, system monitoring',
                'acceptance_criteria' => 'All support requests resolved within SLA',
                'is_milestone' => false,
                'is_billable' => true,
                'tags' => ['support', 'maintenance', 'post-launch'],
            ],
        ];

        foreach ($activities as $activityData) {
            $activity = Activity::create([
                'activity_code' => Activity::generateActivityCode(),
                'title' => $activityData['title'],
                'description' => $activityData['description'],
                'type' => $activityData['type'],
                'priority' => $activityData['priority'],
                'status' => $activityData['status'],
                'project_id' => $projects->random()->id,
                'assigned_to' => $users->random()->id,
                'created_by' => $users->random()->id,
                'planned_start_date' => $activityData['planned_start_date'],
                'planned_end_date' => $activityData['planned_end_date'],
                'actual_start_date' => $activityData['actual_start_date'],
                'actual_end_date' => $activityData['actual_end_date'],
                'estimated_hours' => $activityData['estimated_hours'],
                'actual_hours' => $activityData['actual_hours'],
                'progress_percentage' => $activityData['progress_percentage'],
                'progress_notes' => $activityData['progress_notes'] ?? null,
                'estimated_cost' => $activityData['estimated_cost'],
                'actual_cost' => $activityData['actual_cost'],
                'deliverables' => $activityData['deliverables'],
                'acceptance_criteria' => $activityData['acceptance_criteria'],
                'completion_notes' => $activityData['completion_notes'] ?? null,
                'is_milestone' => $activityData['is_milestone'],
                'is_billable' => $activityData['is_billable'],
                'tags' => $activityData['tags'],
            ]);
        }

        $this->command->info('Created ' . count($activities) . ' sample activities.');
    }
}