<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Contractor;
use App\Models\User;

class ContractorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = User::pluck('id')->toArray();

        $contractorsData = [
            [
                'company_name' => 'GreenTech Solar Solutions',
                'contact_person' => 'Rajesh Kumar Pandey',
                'designation' => 'Managing Director',
                'email' => 'rajesh.kumar@greentech.com',
                'phone' => '9876543210',
                'alternate_phone' => '9123456789',
                'address' => 'Building A, Sector 15 Industrial Area',
                'city' => 'Noida',
                'state' => 'Uttar Pradesh',
                'pincode' => '201301',
                'contractor_type' => 'company',
                'pan_number' => 'ABCDE1234F',
                'gst_number' => '09ABCDE1234F1Z5',
                'specialization' => 'Solar Panel Installation, Electrical Systems',
                'skills' => ['Solar Installation', 'Electrical Wiring', 'Maintenance', 'Commissioning'],
                'experience_description' => 'Specialized in commercial and residential solar installations for over 8 years.',
                'years_of_experience' => 8,
                'hourly_rate' => 500,
                'daily_rate' => 3500,
                'monthly_rate' => 75000,
                'currency' => 'INR',
                'availability' => 'available',
                'status' => 'active',
                'rating' => 4.5,
                'total_projects' => 45,
                'total_value' => 1250000,
                'notes' => 'Reliable contractor with excellent track record.',
                'documents' => ['PAN Certificate', 'Company Registration', 'GST Certificate'],
                'certifications' => ['ISO 9001', 'Solar Installation Certification'],
                'is_verified' => true,
                'verified_at' => '2024-01-15 10:30:00',
            ],
            [
                'company_name' => '',
                'contact_person' => 'Vikram Singh Rawat',
                'designation' => 'Electrical Contractor',
                'email' => 'vikram.singh@gmail.com',
                'phone' => '8765432109',
                'alternate_phone' => '8898765432',
                'address' => 'House No 156, Sukhdev Vihar',
                'city' => 'New Delhi',
                'state' => 'Delhi',
                'pincode' => '110025',
                'contractor_type' => 'individual',
                'pan_number' => 'FGHIJ5678K',
                'gst_number' => '07FGHIJ5678K2Z6',
                'specialization' => 'Solar Panel Installation, DC Wiring',
                'skills' => ['Solar Panel Installation', 'DC Wiring', 'Inverter Setup', 'Battery Installation'],
                'experience_description' => 'Individual contractor specializing in solar installations and electrical work.',
                'years_of_experience' => 6,
                'hourly_rate' => 400,
                'daily_rate' => 2800,
                'monthly_rate' => 60000,
                'currency' => 'INR',
                'availability' => 'on_project',
                'status' => 'active',
                'rating' => 4.2,
                'total_projects' => 32,
                'total_value' => 850000,
                'notes' => 'Excellent individual contractor with good technical skills.',
                'documents' => ['PAN Card', 'Aadhar Card'],
                'certifications' => ['Electrical License', 'Solar Installation Training'],
                'is_verified' => true,
                'verified_at' => '2024-02-10 14:20:00',
            ],
            [
                'company_name' => 'EcoVille Energy Partners',
                'contact_person' => 'Priya Sharma',
                'designation' => 'Project Manager',
                'email' => 'priya.sharma@ecoville.com',
                'phone' => '7654321098',
                'alternate_phone' => '7789012345',
                'address' => 'Office Complex, MG Road',
                'city' => 'Mumbai',
                'state' => 'Maharashtra',
                'pincode' => '400001',
                'contractor_type' => 'partnership',
                'pan_number' => 'KLMNO9012P',
                'gst_number' => '27KLMNO9012P3Z7',
                'specialization' => 'Commercial Solar Projects, Energy Audit',
                'skills' => ['Commercial Solar', 'Energy Audit', 'Project Management', 'Energy Efficiency'],
                'experience_description' => 'Partnership firm focused on commercial solar installations and energy efficiency.',
                'years_of_experience' => 10,
                'hourly_rate' => 750,
                'daily_rate' => 5500,
                'monthly_rate' => 120000,
                'currency' => 'INR',
                'availability' => 'available',
                'status' => 'active',
                'rating' => 4.7,
                'total_projects' => 78,
                'total_value' => 2800000,
                'notes' => 'Highly rated partnership with focus on commercial projects.',
                'documents' => ['Partnership Deed', 'PAN Certificate', 'GST Certificate'],
                'certifications' => ['ISO 14001', 'Commercial Solar Certification'],
                'is_verified' => true,
                'verified_at' => '2024-01-20 09:15:00',
            ],
            [
                'company_name' => 'SunTech Solutions Pvt Ltd',
                'contact_person' => 'Amit Kumar Gupta',
                'designation' => 'Senior Engineer',
                'email' => 'amit.gupta@suntech.com',
                'phone' => '6543210987',
                'alternate_phone' => '6678901234',
                'address' => 'Tech Park, Sector 62',
                'city' => 'Gurugram',
                'state' => 'Haryana',
                'pincode' => '122001',
                'contractor_type' => 'company',
                'pan_number' => 'PQRST3456U',
                'gst_number' => '06PQRST3456U4Z8',
                'specialization' => 'Large Scale Solar Farms, Rooftop Solar',
                'skills' => ['Solar Farm Development', 'Rooftop Solar', 'Grid Connection', 'Monitoring Systems'],
                'experience_description' => 'Leading solar solutions provider for large scale installations.',
                'years_of_experience' => 12,
                'hourly_rate' => 800,
                'daily_rate' => 6000,
                'monthly_rate' => 130000,
                'currency' => 'INR',
                'availability' => 'busy',
                'status' => 'active',
                'rating' => 4.9,
                'total_projects' => 156,
                'total_value' => 5600000,
                'notes' => 'Premium contractor for large scale solar projects.',
                'documents' => ['Company Registration', 'PAN Certificate', 'GST Certificate', 'MSME Certificate'],
                'certifications' => ['ISO 45001', 'Large Scale Solar Certification', 'Grid Connection License'],
                'is_verified' => true,
                'verified_at' => '2024-01-05 11:45:00',
            ],
            [
                'company_name' => '',
                'contact_person' => 'Suresh Agarwal',
                'designation' => 'Solar Installer',
                'email' => 'suresh.agarwal@gmail.com',
                'phone' => '5432109876',
                'alternate_phone' => '5567890123',
                'address' => 'Plot No 45, Model Colony',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411016',
                'contractor_type' => 'individual',
                'pan_number' => 'VWXYZ7890A',
                'gst_number' => '27VWXYZ7890A5Z9',
                'specialization' => 'Residential Solar Installation',
                'skills' => ['Residential Solar', 'Panel Installation', 'Inverter Setup', 'Maintenance'],
                'experience_description' => 'Experienced individual contractor for residential solar installations.',
                'years_of_experience' => 5,
                'hourly_rate' => 350,
                'daily_rate' => 2500,
                'monthly_rate' => 50000,
                'currency' => 'INR',
                'availability' => 'available',
                'status' => 'active',
                'rating' => 4.1,
                'total_projects' => 28,
                'total_value' => 420000,
                'notes' => 'Reliable contractor for residential installations.',
                'documents' => ['PAN Card', 'Aadhar Card'],
                'certifications' => ['Solar Installation Certificate'],
                'is_verified' => false,
                'verified_at' => null,
            ],
            [
                'company_name' => 'PowerGen Associates',
                'contact_person' => 'Anita Verma',
                'designation' => 'Director',
                'email' => 'anita.verma@powergen.com',
                'phone' => '4321098765',
                'alternate_phone' => '4456789012',
                'address' => 'Business Center, Sector 17',
                'city' => 'Chandigarh',
                'state' => 'Punjab',
                'pincode' => '160017',
                'contractor_type' => 'partnership',
                'pan_number' => 'BCDEF1234G',
                'gst_number' => '03BCDEF1234G6Z0',
                'specialization' => 'Hybrid Solar Systems, Battery Storage',
                'skills' => ['Hybrid Systems', 'Battery Storage', 'Smart Inverters', 'Energy Management'],
                'experience_description' => 'Specialized in hybrid solar systems with battery storage solutions.',
                'years_of_experience' => 7,
                'hourly_rate' => 600,
                'daily_rate' => 4500,
                'monthly_rate' => 95000,
                'currency' => 'INR',
                'availability' => 'unavailable',
                'status' => 'active',
                'rating' => 4.3,
                'total_projects' => 52,
                'total_value' => 1800000,
                'notes' => 'Expert in hybrid solar and battery storage systems.',
                'documents' => ['Partnership Deed', 'PAN Certificate', 'GST Certificate'],
                'certifications' => ['Hybrid Systems Certification', 'Battery Storage Training'],
                'is_verified' => true,
                'verified_at' => '2024-02-05 15:30:00',
            ],
            [
                'company_name' => 'EcoSolar Services',
                'contact_person' => 'Deepak Joshi',
                'designation' => 'Lead Technician',
                'email' => 'deepak.joshi@ecosolar.com',
                'phone' => '3210987654',
                'alternate_phone' => '3345678901',
                'address' => 'Industrial Estate, Phase II',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560001',
                'contractor_type' => 'subcontractor',
                'pan_number' => 'GHIJK5678L',
                'gst_number' => '29GHIJK5678L7Z1',
                'specialization' => 'Solar Panel Maintenance & Repair',
                'skills' => ['Solar Maintenance', 'Panel Repair', 'Inverter Repair', 'System Diagnosis'],
                'experience_description' => 'Subcontractor specializing in solar system maintenance and repairs.',
                'years_of_experience' => 4,
                'hourly_rate' => 300,
                'daily_rate' => 2000,
                'monthly_rate' => 40000,
                'currency' => 'INR',
                'availability' => 'available',
                'status' => 'active',
                'rating' => 3.9,
                'total_projects' => 35,
                'total_value' => 280000,
                'notes' => 'Specialist in solar system maintenance and repairs.',
                'documents' => ['PAN Certificate', 'GST Certificate'],
                'certifications' => ['Solar Maintenance Certificate'],
                'is_verified' => false,
                'verified_at' => null,
            ],
            [
                'company_name' => 'GreenFuture Enterprises',
                'contact_person' => 'Meera Kumari',
                'designation' => 'Technical Head',
                'email' => 'meera.kumari@greenfuture.com',
                'phone' => '2109876543',
                'alternate_phone' => '2234567890',
                'address' => 'Corporate Plaza, Financial District',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500032',
                'contractor_type' => 'company',
                'pan_number' => 'LMNOP9012Q',
                'gst_number' => '36LMNOP9012Q8Z2',
                'specialization' => 'Industrial Solar Solutions',
                'skills' => ['Industrial Solar', 'High Voltage Systems', 'Power Distribution', 'Custom Solutions'],
                'experience_description' => 'Leading provider of industrial solar solutions and power systems.',
                'years_of_experience' => 15,
                'hourly_rate' => 1000,
                'daily_rate' => 7500,
                'monthly_rate' => 160000,
                'currency' => 'INR',
                'availability' => 'available',
                'status' => 'active',
                'rating' => 4.8,
                'total_projects' => 89,
                'total_value' => 4200000,
                'notes' => 'Premium contractor for industrial solar solutions.',
                'documents' => ['Company Registration', 'PAN Certificate', 'GST Certificate', 'Industrial License'],
                'certifications' => ['ISO 27001', 'Industrial Solar Certification', 'High Voltage License'],
                'is_verified' => true,
                'verified_at' => '2024-01-12 16:20:00',
            ],
            [
                'company_name' => '',
                'contact_person' => 'Ravindra Kumar',
                'designation' => 'Solar Technician',
                'email' => 'ravindra.kumar@email.com',
                'phone' => '1098765432',
                'alternate_phone' => '1123456789',
                'address' => 'Street No 5, Old Delhi',
                'city' => 'New Delhi',
                'state' => 'Delhi',
                'pincode' => '110006',
                'contractor_type' => 'individual',
                'pan_number' => 'QRSTU3456V',
                'gst_number' => '07QRSTU3456V9Z3',
                'specialization' => 'Off-Grid Solar Systems',
                'skills' => ['Off-Grid Systems', 'Battery Management', 'Charge Controllers', 'Panel Installation'],
                'experience_description' => 'Specialized in off-grid solar systems for remote locations.',
                'years_of_experience' => 6,
                'hourly_rate' => 450,
                'daily_rate' => 3200,
                'monthly_rate' => 65000,
                'currency' => 'INR',
                'availability' => 'on_project',
                'status' => 'active',
                'rating' => 4.4,
                'total_projects' => 41,
                'total_value' => 780000,
                'notes' => 'Expert in off-grid solar solutions.',
                'documents' => ['PAN Card', 'Aadhar Card'],
                'certifications' => ['Off-Grid Systems Certificate'],
                'is_verified' => true,
                'verified_at' => '2024-02-15 10:10:00',
            ],
            [
                'company_name' => 'CleanEnergy Solutions',
                'contact_person' => 'Naresh Patel',
                'designation' => 'Project Engineer',
                'email' => 'naresh.patel@cleanenergy.com',
                'phone' => '0987654321',
                'alternate_phone' => '1012345678',
                'address' => 'Innovation Hub, IT Park',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600001',
                'contractor_type' => 'company',
                'pan_number' => 'UVWXY7890Z',
                'gst_number' => '33UVWXY7890Z0Z4',
                'specialization' => 'Solar Water Heating Systems',
                'skills' => ['Solar Water Heating', 'Thermal Systems', 'Plumbing', 'System Integration'],
                'experience_description' => 'Specialized in solar water heating and thermal solar systems.',
                'years_of_experience' => 9,
                'hourly_rate' => 550,
                'daily_rate' => 4000,
                'monthly_rate' => 85000,
                'currency' => 'INR',
                'availability' => 'available',
                'status' => 'active',
                'rating' => 4.0,
                'total_projects' => 67,
                'total_value' => 1900000,
                'notes' => 'Specialist in solar water heating systems.',
                'documents' => ['Company Registration', 'PAN Certificate', 'GST Certificate'],
                'certifications' => ['Solar Thermal Certificate', 'Plumbing License'],
                'is_verified' => false,
                'verified_at' => null,
            ],
            [
                'company_name' => '',
                'contact_person' => 'Abdul Rahman Khan',
                'designation' => 'Solar Installer',
                'email' => 'abdul.khan@solar.com',
                'phone' => '9876543218',
                'alternate_phone' => '9988776655',
                'address' => 'House No 45, Malviya Nagar',
                'city' => 'Jaipur',
                'state' => 'Rajasthan',
                'pincode' => '302017',
                'contractor_type' => 'individual',
                'pan_number' => 'ABCDE9876F',
                'gst_number' => '08ABCDE9876F1Z5',
                'specialization' => 'Residential Solar & Backup Systems',
                'skills' => ['Residential Solar', 'Backup Systems', 'Energy Storage', 'Inverter Installation'],
                'experience_description' => 'Individual contractor for residential solar with backup systems.',
                'years_of_experience' => 7,
                'hourly_rate' => 400,
                'daily_rate' => 2800,
                'monthly_rate' => 60000,
                'currency' => 'INR',
                'availability' => 'available',
                'status' => 'suspended',
                'rating' => 2.5,
                'total_projects' => 23,
                'total_value' => 340000,
                'notes' => 'Contractor suspended due to quality issues.',
                'documents' => ['PAN Card'],
                'certifications' => [],
                'is_verified' => false,
                'verified_at' => null,
            ],
        ];

        foreach ($contractorsData as $data) {
            Contractor::create(array_merge($data, [
                'created_by' => fake()->randomElement($users),
                'assigned_to' => fake()->randomElement($users),
                'verified_by' => $data['is_verified'] ? fake()->randomElement($users) : null,
            ]));
        }
    }
}