<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PaymentMilestone;
use App\Models\Project;
use App\Models\Quotation;
use App\Models\User;

class PaymentMilestoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $projects = Project::pluck('id')->toArray();
        $quotations = Quotation::pluck('id')->toArray();
        $users = User::pluck('id')->toArray();

        $milestonesData = [
            [
                'title' => 'Advance Payment - Project Setup',
                'description' => 'Initial advance payment for project setup and mobilization',
                'milestone_amount' => 50000,
                'paid_amount' => 50000,
                'milestone_type' => 'advance',
                'milestone_percentage' => 100,
                'planned_date' => '2024-01-15',
                'due_date' => '2024-01-20',
                'payment_date' => '2024-01-18',
                'status' => 'paid',
                'payment_status' => 'paid',
                'payment_method' => 'bank_transfer',
                'payment_reference' => 'TXN-001-ADV',
                'payment_notes' => 'Advance payment received as per terms',
                'milestone_notes' => 'Project setup completed on time',
            ],
            [
                'title' => 'First Progress Payment - Foundation Work',
                'description' => 'Payment for foundation and initial construction work',
                'milestone_amount' => 150000,
                'paid_amount' => 150000,
                'milestone_type' => 'progress',
                'milestone_percentage' => 100,
                'planned_date' => '2024-02-15',
                'due_date' => '2024-02-20',
                'payment_date' => '2024-02-18',
                'status' => 'paid',
                'payment_status' => 'paid',
                'payment_method' => 'bank_transfer',
                'payment_reference' => 'TXN-002-PROG1',
                'payment_notes' => 'Progress payment after foundation completion',
                'milestone_notes' => 'Foundation work completed ahead of schedule',
            ],
            [
                'title' => 'Second Progress Payment - Structure Work',
                'description' => 'Payment for structural steel installation and framework',
                'milestone_amount' => 200000,
                'paid_amount' => 100000,
                'milestone_type' => 'progress',
                'milestone_percentage' => 80,
                'planned_date' => '2024-03-15',
                'due_date' => '2024-03-20',
                'payment_date' => '2024-03-18',
                'status' => 'in_progress',
                'payment_status' => 'partial',
                'payment_method' => 'bank_transfer',
                'payment_reference' => 'TXN-003-PROG2',
                'payment_notes' => 'Partial payment - remaining after completion',
                'milestone_notes' => 'Structure work 80% complete',
            ],
            [
                'title' => 'Third Progress Payment - Installation Phase',
                'description' => 'Payment for solar panel installation and electrical work',
                'milestone_amount' => 180000,
                'paid_amount' => 0,
                'milestone_type' => 'progress',
                'milestone_percentage' => 30,
                'planned_date' => '2024-05-01',
                'due_date' => '2024-05-05',
                'payment_date' => null,
                'status' => 'in_progress',
                'payment_status' => 'pending',
                'payment_method' => null,
                'payment_reference' => null,
                'payment_notes' => null,
                'milestone_notes' => 'Installation phase in progress',
            ],
            [
                'title' => 'Completion Payment - Final Installation',
                'description' => 'Payment upon project completion and commissioning',
                'milestone_amount' => 300000,
                'paid_amount' => 0,
                'milestone_type' => 'completion',
                'milestone_percentage' => 0,
                'planned_date' => '2024-06-01',
                'due_date' => '2024-06-05',
                'payment_date' => null,
                'status' => 'pending',
                'payment_status' => 'pending',
                'payment_method' => null,
                'payment_reference' => null,
                'payment_notes' => null,
                'milestone_notes' => 'Pending project completion',
            ],
            [
                'title' => 'Retention Payment - Warranty Period',
                'description' => 'Final retention payment after warranty period',
                'milestone_amount' => 75000,
                'paid_amount' => 0,
                'milestone_type' => 'retention',
                'milestone_percentage' => 0,
                'planned_date' => '2024-12-01',
                'due_date' => '2024-12-05',
                'payment_date' => null,
                'status' => 'pending',
                'payment_status' => 'pending',
                'payment_method' => null,
                'payment_reference' => null,
                'payment_notes' => null,
                'milestone_notes' => 'Warranty retention - payable after 6 months',
            ],
            [
                'title' => 'Advance Payment - Second Phase',
                'description' => 'Advance payment for Phase 2 expansion project',
                'milestone_amount' => 80000,
                'paid_amount' => 40000,
                'milestone_type' => 'advance',
                'milestone_percentage' => 60,
                'planned_date' => '2024-04-01',
                'due_date' => '2024-04-05',
                'payment_date' => '2024-03-30',
                'status' => 'in_progress',
                'payment_status' => 'partial',
                'payment_method' => 'online',
                'payment_reference' => 'TXN-004-ADV2',
                'payment_notes' => 'Partial advance payment',
                'milestone_notes' => 'Phase 2 project initiated',
            ],
            [
                'title' => 'Equipment Installation Milestone',
                'description' => 'Payment for specialized equipment installation',
                'milestone_amount' => 120000,
                'paid_amount' => 120000,
                'milestone_type' => 'final',
                'milestone_percentage' => 100,
                'planned_date' => '2024-03-01',
                'due_date' => '2024-03-10',
                'payment_date' => '2024-03-08',
                'status' => 'paid',
                'payment_status' => 'paid',
                'payment_method' => 'cheque',
                'payment_reference' => 'CHQ-789456',
                'payment_notes' => 'Equipment installation completed',
                'milestone_notes' => 'All equipment installed and tested',
            ],
            [
                'title' => 'Overdue Progress Payment',
                'description' => 'Progress payment for completion milestone - OVERDUE',
                'milestone_amount' => 95000,
                'paid_amount' => 0,
                'milestone_type' => 'progress',
                'milestone_percentage' => 90,
                'planned_date' => '2024-02-01',
                'due_date' => '2024-02-15',
                'payment_date' => null,
                'status' => 'overdue',
                'payment_status' => 'overdue',
                'payment_method' => null,
                'payment_reference' => null,
                'payment_notes' => null,
                'milestone_notes' => 'Payment overdue - follow up required',
            ],
            [
                'title' => 'Commissioning Payment',
                'description' => 'Final commissioning and handover payment',
                'milestone_amount' => 55000,
                'paid_amount' => 0,
                'milestone_type' => 'final',
                'milestone_percentage' => 0,
                'planned_date' => '2024-07-15',
                'due_date' => '2024-07-20',
                'payment_date' => null,
                'status' => 'pending',
                'payment_status' => 'pending',
                'payment_method' => null,
                'payment_reference' => null,
                'payment_notes' => null,
                'milestone_notes' => 'Commissioning milestone pending',
            ],
            [
                'title' => 'Emergency Repair Milestone',
                'description' => 'Additional payment for emergency repairs',
                'milestone_amount' => 25000,
                'paid_amount' => 0,
                'milestone_type' => 'final',
                'milestone_percentage' => 0,
                'planned_date' => '2024-04-15',
                'due_date' => '2024-04-20',
                'payment_date' => null,
                'status' => 'pending',
                'payment_status' => 'pending',
                'payment_method' => null,
                'payment_reference' => null,
                'payment_notes' => null,
                'milestone_notes' => 'Emergency repairs approved',
            ],
            [
                'title' => 'Maintenance Contract Milestone',
                'description' => 'Payment for annual maintenance contract',
                'milestone_amount' => 40000,
                'paid_amount' => 0,
                'milestone_type' => 'final',
                'milestone_percentage' => 0,
                'planned_date' => '2024-12-15',
                'due_date' => '2024-12-20',
                'payment_date' => null,
                'status' => 'pending',
                'payment_status' => 'pending',
                'payment_method' => null,
                'payment_reference' => null,
                'payment_notes' => null,
                'milestone_notes' => 'Annual maintenance contract milestone',
            ],
        ];

        foreach ($milestonesData as $data) {
            PaymentMilestone::create(array_merge($data, [
                'project_id' => count($projects) > 0 ? fake()->randomElement($projects) : null,
                'quotation_id' => count($quotations) > 0 ? fake()->randomElement($quotations) : null,
                'created_by' => fake()->randomElement($users),
                'assigned_to' => fake()->randomElement($users),
                'paid_by' => $data['payment_status'] === 'paid' || $data['payment_status'] === 'partial' ? fake()->randomElement($users) : null,
                'paid_at' => $data['payment_status'] === 'paid' || $data['payment_status'] === 'partial' ? fake()->dateTimeBetween($data['payment_date'], now()) : null,
                'currency' => fake()->randomElement(['INR', 'USD', 'EUR']),
            ]));
        }
    }
}